### ISSUE TITLE
Problema associado com tela em branco no seu app

### ISSUE THREAD

**Issue by leopoldomt** [amandaca24/kotlin-android-podcast#1]
A bronca está nas linhas a seguir. Elas estão confundindo o sistema, que acha que deve ser aberta a `EpisodeActivity` ao invés de `MainActivity`. 

https://github.com/amandaca24/kotlin-android-podcast/blob/1407ddd27e6044a48031421d18ce2922ed79449a/app/src/main/AndroidManifest.xml#L18-L22

**Comment by leopoldomt** [comment]
@amandaca24

**Comment by amandaca24** [comment]
Corrigi e apareceu a main direitinho, com o feed padrão. Mas o problema ainda continua na EpisodeActivity... ele tá pulando o layout dizendo que não tem adapter...

**Comment by leopoldomt** [comment]
O problema está na linha abaixo: 
https://github.com/amandaca24/kotlin-android-podcast/blob/1407ddd27e6044a48031421d18ce2922ed79449a/app/src/main/java/br/ufpe/cin/android/podcast/EpisodeActivity.kt#L40

Ao dar `setContentView` passando uma referência para `R.layout.activity_episode` ao invés de `binding.root` isso faz com que um novo processo de inflar o XML (`inflate`) seja executado, criando novos objetos de UI. Ou seja, ao dar o `apply` para configurar o `RecyclerView` com o `EpisodeAdapter`, não está sendo modificado o que está sendo exibido na tela.

**Comment by amandaca24** [comment]
Boa, deu certo!! Agora vou passar para as próximas etapas. Valeu, @leopoldomt!!!
