### ISSUE TITLE
problema de download

### ISSUE THREAD

**Issue by leopoldomt** [amandaca24/kotlin-android-podcast#2]
Você só vai atualizar o conteúdo dos `TextView` na hora que rodar o observer nas linhas a seguir: 
https://github.com/amandaca24/kotlin-android-podcast/blob/76f6b28fa76473bddb7a70a5a82503242ef9bb21/app/src/main/java/br/ufpe/cin/android/podcast/EpisodeDetailActivity.kt#L61-L70

O problema é que você está chamando o `WorkManager` imediatamente (vide linhas abaixo) 
https://github.com/amandaca24/kotlin-android-podcast/blob/76f6b28fa76473bddb7a70a5a82503242ef9bb21/app/src/main/java/br/ufpe/cin/android/podcast/EpisodeDetailActivity.kt#L72-L79

O worker está sendo chamado/enfileirado antes de terminar de fazer a consulta `episodeViewModel.findByTitle(titleDownload)`. Ou seja, ainda não deu tempo de atualizar o conteúdo do `TextView` e ele usa o texto padrão disponível em: 
https://github.com/amandaca24/kotlin-android-podcast/blob/76f6b28fa76473bddb7a70a5a82503242ef9bb21/app/src/main/res/layout/activity_episode_detail.xml#L26-L30

Se você trocar o texto no XML para X vai aparecer o erro `java.net.MalformedURLException: no protocol: X`.

**Comment by amandaca24** [comment]
@leopoldomt deu certo aqui! Valeu, professor.
